/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as FinanceiroUploadRouteImport } from './routes/financeiro.upload'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroUploadRoute = FinanceiroUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => FinanceiroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/login': typeof LoginRoute
  '/financeiro/upload': typeof FinanceiroUploadRoute
  '/financeiro/': typeof FinanceiroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/financeiro/upload': typeof FinanceiroUploadRoute
  '/financeiro': typeof FinanceiroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/login': typeof LoginRoute
  '/financeiro/upload': typeof FinanceiroUploadRoute
  '/financeiro/': typeof FinanceiroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/financeiro'
    | '/login'
    | '/financeiro/upload'
    | '/financeiro/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/financeiro/upload' | '/financeiro'
  id:
    | '__root__'
    | '/'
    | '/financeiro'
    | '/login'
    | '/financeiro/upload'
    | '/financeiro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/upload': {
      id: '/financeiro/upload'
      path: '/upload'
      fullPath: '/financeiro/upload'
      preLoaderRoute: typeof FinanceiroUploadRouteImport
      parentRoute: typeof FinanceiroRoute
    }
  }
}

interface FinanceiroRouteChildren {
  FinanceiroUploadRoute: typeof FinanceiroUploadRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroUploadRoute: FinanceiroUploadRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
